apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app-ingress
  namespace: sample-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: <ec2_public_ip>.nip.io # Replace <ec2_public_ip> with your EC2 instance's public IP
    http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: sample-app
          port:
            number: 80